apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave

