apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      volumes:
      - name: ssl
        hostPath:
          path: /etc/ssl
      - name: ca
        hostPath:
          path: /usr/share/ca-certificates
      containers:
      - image: quay.io/philips/guestbook:v2
        imagePullPolicy: Always
        name: guestbook
        volumeMounts:
          - mountPath: /etc/ssl
            name: ssl
          - mountPath: /usr/share/ca-certificates
            name: ca
        ports:
        - containerPort: 3000
          name: http-server
        env:
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: twilio
                key: sid
          - name: TWILIO_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: twilio
                key: token

