apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master

