apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - image: kubernetes/redis-slave:v2
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server
